### ISSUE TITLE
3.1.0 todo list

### ISSUE THREAD

**Issue by razaqq** [razaqq/PotatoAlert#26]
- [ ] Window border goes outside screen in fullscreen, this already exists in 3.0.1
- [ ] Double check initializer lists
- [ ] Implement changelog
- [ ] Investigate window size reset/config saving issue
- [ ] Match history
- [ ] Integrate python stringtable generation in cmake
- [ ] Make use of Q_PROPERTY
- [ ] Ship icons
- [ ] Team WR diff in match history?
- [ ] Installer (nullsoft?, https://github.com/QuasarApp/CQtDeployer)
- [ ] Overwrite region when no game selected - currently when using a replays folder override with no game selected, the region is empty
- [ ] Detect game install from registry (`PotatoAlert::Game::GetGamePath()`)
- [ ] Rename util to core
