### ISSUE TITLE
3.2.0 TODO List

### ISSUE THREAD

**Issue by razaqq** [razaqq/PotatoAlert#29]
- [x] Ship icons
- [ ] Implement changelog
- [ ] Team WR diff in match history?
- [x] Installer (nullsoft?, https://github.com/QuasarApp/CQtDeployer)
- [x] Qt6
- [x] `std::expected`
- [ ] replace pickler with c++
- [ ] https://github.com/corrosion-rs/corrosion#cmake-install
- [ ] linking LTO in debug mode - LLD crash
- [x] arrow key controls
- [ ] region icon instead of text in cw
- [x] dependency injection
- [ ] match summary popup ribbons
- [ ] rewrite updater or use a pre-built solution
- [ ] relation enum class Relation{ Self = 0, Friendly = 1, Enemy = 2 }
- [ ] split statsparser and gui
- [x] stats parser fields CamelCase
- [ ] maybe change licensing
- [ ] SMBIOS
- [ ] Opt-in beta versions
- [x] Add option to change team average to weighted, average, median
- [x] Investigate high DPI issues
- [ ] https://replayswows.com/ integration
- [x] replace remaining pngs with svgs (loading anim, error)
- [ ] ReplaySummary Team Score
- [x] separate option to save csv
- [ ] https://github.com/btzy/nativefiledialog-extended
- [ ] https://github.com/stephenberry/glaze
